### PR TITLE
Bug fixes, quality of life changes, visual changes

### LINKED ISSUE #103: NumberFieldControllers increase their values by ^10 when clicking on screen
When using a FloatFieldController or DoubleFieldController there seems to be an error on how the number is read back from the input field.
Everytime you click on an area that is not the option, the value increases by ^10 with some exceptions.
Another issue is, that you cannot close the config screen, because every time you click on done/save changes, the values are changed.

This bug occours on version '3.1.0+1.20 (Fabric)' and was tested by me and a friend in seperate projects.
_edit: version '3.1.1+1.20 (Fabric)' is also affected._

#### Showcase video:
https://github.com/isXander/YetAnotherConfigLib/assets/42215949/fab793d1-9aaf-42df-9dd2-aa9cf03aa6f7

Code from the video (written in Kotlin):
```kotlin
    private const val TEST_FLOAT_DEFAULT = 0.00002f
    private var testFloat = 0f

    private fun buildTestFloat() =
        Option.createBuilder<Float>()
            .name(Text.of("Float Test"))
            .description { it ->
                OptionDescription.of(Text.of("""
                    This is a test option for floats.
                    It has a default value of $TEST_FLOAT_DEFAULT.
                    Current value: $it
                    """.trimIndent()))
            }
            .binding(TEST_FLOAT_DEFAULT, { testFloat }, { it -> testFloat = it })
            .controller { it ->
                FloatFieldControllerBuilder.create(it).valueFormatter { Text.literal(it.toString()) }
            }.build()
```
_Here I'm using `Text.literal(it.toString())` but the results are the same if you use the default formatter or any other._

### PR DESCRIPTION
**Pull request by Rasmion**
### Bug fixes:
- Fixes #103 
- Fixes values not updating when unfocusing a StringControllerElement
- Fixes a bug where the caret isn't rendered if the caretPos is 0

### Quality of life changes:
- Support for `home` and `end` key
- Additional functionality for `Ctrl + Left/Right` (now you can jump over words, even without selecting text)
- Changes `findSpaceIndex` to be more consistent with other programs like Word

### Visual changes:
- Caret now pauses flickering for a bit after moving
- Positions caret and selection at the same height as the text and give them new bounds
- Render caret on top of the selection and not behind it

https://github.com/isXander/YetAnotherConfigLib/assets/42215949/4a0304e9-90f3-4066-8931-69826b1c9d2e

### CODE REVIEW

File: common/src/main/java/dev/isxander/yacl3/gui/controllers/string/number/NumberFieldController.java [hunk 1]
```diff
@@ -20,6 +26,21 @@
...
+
+    private static final List<Character> ALLOWED_CHARS = Util.make(() -> {
+        List<Character> chars = new ArrayList<>();
+        DecimalFormatSymbols symbols = DecimalFormatSymbols.getInstance();
+        chars.add(symbols.getDecimalSeparator());
+        chars.add(symbols.getMinusSign());
+        chars.add(symbols.getZeroDigit());
+        chars.add(symbols.getGroupingSeparator());
+        symbols.getExponentSeparator().chars().mapToObj(i -> (char) i).forEach(chars::add);
+        "123456789".chars().mapToObj(i -> (char) i).forEach(chars::add);
```
Comment (isXander) [inline common/src/main/java/dev/isxander/yacl3/gui/controllers/string/number/NumberFieldController.java:40]: did you forget `0`?

File: common/src/main/java/dev/isxander/yacl3/gui/controllers/string/number/NumberFieldController.java [hunk 2]
```diff
@@ -46,7 +70,7 @@ public double pendingValue() {
 
     @Override
     public boolean isInputValid(String input) {
-        return input.matches("[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)|[.]||-");
+        return input.chars().allMatch(i -> ALLOWED_CHARS.contains((char) i));
```
Comment (isXander) [inline common/src/main/java/dev/isxander/yacl3/gui/controllers/string/number/NumberFieldController.java:73]: this allows multiple decimal places does it not?

**Review by isXander — APPROVED** [review]

**Review by isXander — APPROVED** [review]
